import "@/app/ui/global.css";
import {Analytics} from "@vercel/analytics/next";
import {SpeedInsights} from "@vercel/speed-insights/next";
import {QueryProvider} from "@/app/shared/api/queryProvider";
import NextTopLoader from "nextjs-toploader";
import {
    ClerkProvider,
    SignedOut,
} from "@clerk/nextjs";
import {Metadata} from "next";
import {ruRU} from "@clerk/localizations";
import {Geist, Geist_Mono} from 'next/font/google'
import {experimental__simple} from "@clerk/themes"
import {ThemeProvider} from "next-themes";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Clerk Next.js Quickstart",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider
            localization={ruRU}
            appearance={{
                baseTheme: experimental__simple
            }}
        >
            {/*https://ui.shadcn.com/docs/dark-mode/next*/}
            <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <SignedOut>
                {/*! I don't need it in my setup - all routes are private*/}
                {/*<SignInButton/>*/}
                {/*<SignUpButton>*/}
                {/*    <button*/}
                {/*        className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">*/}
                {/*        Sign Up*/}
                {/*    </button>*/}
                {/*</SignUpButton>*/}
            </SignedOut>
            <NextTopLoader color="#2A2F3C" showSpinner={false} shadow-sm="none"/>
            <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem
                disableTransitionOnChange
            >
                <QueryProvider>
                    {children}
                </QueryProvider>
            </ThemeProvider>
            </body>
            <SpeedInsights/>
            <Analytics/>
            </html>
        </ClerkProvider>
    );
}
